const tasks={
individu:[
{id:"i1",number:1,title:"Follow semua akun Sosmed PGSD & HMP PGSD",deadline:"2026-09-11T23:59:00+07:00",deadlineText:"Jumat, 11 September 2026 • 23.59 WIB",details:`<strong>Wajib follow/subscribe:</strong><p class="social-hint">🔗 Klik logo untuk mengunjungi akun</p><div class="social-links"><a class="social-link" href="https://www.instagram.com/pgsd.unesa" target="_blank" rel="noopener noreferrer"><img src="https://cdn.simpleicons.org/instagram" alt="Instagram"><span>Instagram<br><small>@pgsd.unesa</small></span></a><a class="social-link" href="https://www.instagram.com/hmppgsd_unesa" target="_blank" rel="noopener noreferrer"><img src="https://cdn.simpleicons.org/instagram" alt="Instagram"><span>Instagram<br><small>@hmppgsd_unesa</small></span></a><a class="social-link" href="https://www.instagram.com/ppkpgsd_unesa" target="_blank" rel="noopener noreferrer"><img src="https://cdn.simpleicons.org/instagram" alt="Instagram"><span>Instagram<br><small>@ppkpgsd_unesa</small></span></a><a class="social-link" href="https://www.tiktok.com/@pgsd.unesa" target="_blank" rel="noopener noreferrer"><img src="https://cdn.simpleicons.org/tiktok" alt="TikTok"><span>TikTok<br><small>@pgsd.unesa</small></span></a><a class="social-link" href="https://www.tiktok.com/@hmppgsdunesa" target="_blank" rel="noopener noreferrer"><img src="https://cdn.simpleicons.org/tiktok" alt="TikTok"><span>TikTok<br><small>@hmppgsdunesa</small></span></a><a class="social-link" href="https://youtube.com/@pgsdunesa" target="_blank" rel="noopener noreferrer"><img src="https://cdn.simpleicons.org/youtube" alt="YouTube"><span>YouTube<br><small>PGSDUNESA</small></span></a><a class="social-link" href="https://open.spotify.com/show/3iNiFcj5XHakknAKKajGQr" target="_blank" rel="noopener noreferrer"><img src="https://cdn.simpleicons.org/spotify" alt="Spotify"><span>Spotify<br><small>hmppgsd unesa</small></span></a></div><strong>Bukti:</strong> Screenshot akun yang di-follow dan kirim ke Google Drive kelompok.<br><br>Gunakan akun pribadi aktif.`},
{id:"i2",number:2,title:"Upload Twibbon",deadline:"2026-09-03T23:59:00+07:00",deadlineText:"Kamis, 3 September 2026 • 23.59 WIB",resourceUrl:"https://drive.google.com/drive/folders/1BTRRkNPuKU3405Ott4BNOf5DuigsUAhl",resourceLabel:"Buka Folder Twibbon",details:"<ul><li>Gunakan template Twibbon resmi.</li><li>Upload di Instagram pribadi.</li><li>Foto bebas, santai, tetap sopan.</li><li>Akun tidak boleh private.</li><li>Tag kakak pembimbing dan @hmppgsd_unesa.</li></ul>"},
{id:"i3",number:3,title:"Cetak ID Card",deadline:"2026-09-11T23:59:00+07:00",deadlineText:"Jumat, 11 September 2026 • 23.59 WIB",resourceUrl:"https://drive.google.com/drive/folders/1j-xHjZQVSq27HcAaW_-qIxWk4bvPphUx",resourceLabel:"Buka Folder ID Card",details:"<ul><li>Template resmi, A4 full.</li><li>Tali pita merah maroon lebar 1,5 cm.</li><li>Panjang tali sesuai tinggi badan.</li><li>Nama lengkap, kelompok, motto hidup dengan spidol hitam kecil.</li><li>Laminasi dengan desain sekitar 1 cm.</li><li>Buat lubang kanan-kiri untuk tali dan ikat rapi.</li></ul>"},
{id:"i4",number:4,title:"Quiz",deadline:null,deadlineText:"Maksimal 2 jam setelah link quiz dibagikan",details:"<ul><li>Soal berdasarkan materi.</li><li>Dikerjakan melalui link quiz.</li><li>Pilihan ganda.</li><li>Hanya 1 jawaban benar.</li></ul>"},
{id:"i5",number:5,title:"Resume materi dalam bentuk infografis",deadline:null,deadlineText:"3 sub-tugas Day 1–3",details:"<p>Buat 2 infografis untuk materi Day 1, Day 2, dan Day 3.</p><ul><li>Menarik, ringkas, informatif.</li><li>Upload Instagram Story pribadi dan tag IG kelas.</li><li>Repost ke grup sebagai bukti.</li><li>Masukkan ke Highlight IG kelas.</li><li>Akun tidak private.</li><li>Boleh Canva, PowerPoint, dll.</li></ul>",subtasks:[
{id:"inf1",title:"Infografis Day 1",deadline:"2026-09-12T23:59:00+07:00",deadlineText:"12 September 2026 • 23.59"},
{id:"inf2",title:"Infografis Day 2",deadline:"2026-09-19T23:59:00+07:00",deadlineText:"19 September 2026 • 23.59"},
{id:"inf3",title:"Infografis Day 3",deadline:"2026-10-03T23:59:00+07:00",deadlineText:"3 Oktober 2026 • 23.59"}]},
{id:"i6",number:6,title:"Resume berupa review materi — Vlog",deadline:null,deadlineText:"3 sub-tugas Day 1–3",details:"<p>Buat 3 vlog untuk Day 1, Day 2, Day 3.</p><strong>Isi:</strong><ol><li>Cerita pengalaman kegiatan.</li><li>Review materi + praktik.</li><li>Refleksi.</li></ol><strong>Ketentuan:</strong><ul><li>Maksimal 1 menit/video.</li><li>Kreatif, jelas, komunikatif.</li><li>Upload TikTok pribadi.</li><li>Caption sesuai isi.</li><li>Tag pembimbing + HMP.</li><li>#PPPKPGSD #PPPK2026 #VlogPPPK</li><li>Akun tidak private.</li></ul>",subtasks:[
{id:"vlog1",title:"Vlog Day 1",deadline:"2026-09-13T23:59:00+07:00",deadlineText:"13 September 2026 • 23.59"},
{id:"vlog2",title:"Vlog Day 2",deadline:"2026-09-20T23:59:00+07:00",deadlineText:"20 September 2026 • 23.59"},
{id:"vlog3",title:"Vlog Day 3",deadline:"2026-10-04T23:59:00+07:00",deadlineText:"4 Oktober 2026 • 23.59"}]},
{id:"i7",number:7,title:"Tukar Kado + Tantangan Rahasia",deadline:"2026-09-19T23:59:00+07:00",deadlineText:"Sabtu, 19 September 2026",details:"<ul><li>Budget Rp10.000.</li><li>Bungkus rapi dengan kertas glossy merah.</li><li>Tanpa nama pemberi.</li><li>Selipkan 1 misi/tantangan kecil.</li><li>Isi bebas dan tidak mudah basi.</li><li>Tantangan tidak boleh menghina, merugikan, SARA, atau mempermalukan berlebihan.</li><li>Jaga kejutan; tukar secara acak.</li></ul>"},
{id:"i8",number:8,title:"Profil DPA",deadline:"2026-10-05T23:59:00+07:00",deadlineText:"Senin, 5 Oktober 2026",details:"<strong>Isi:</strong><ol><li>Nama lengkap dan gelar.</li><li>NIP/NIDN.</li><li>Jabatan fungsional.</li><li>Bidang keahlian/mata kuliah.</li><li>Riwayat pendidikan.</li><li>Tempat tugas, fakultas, program studi.</li><li>Motto, prestasi, atau kutipan DPA.</li></ol><strong>Ketentuan:</strong> Ditulis tangan, tidak menyalin profil teman. Foto opsional. Sumber dapat dari website universitas, Google Scholar, SINTA, portal akademik, atau media sosial DPA."}
],
kelompok:[
{id:"k1",number:1,title:"Membentuk Pengurus Kelas",deadline:"2026-09-05T23:59:00+07:00",deadlineText:"Sabtu, 5 September 2026",details:"<strong>Harus menentukan:</strong><ul><li>Ketua kelas</li><li>Wakil ketua</li><li>Sekretaris</li><li>Bendahara</li></ul>Hasil diskusi dilaporkan ke grup kelompok masing-masing."},
{id:"k2",number:2,title:"Membuat Instagram Kelas",deadline:"2026-09-05T23:59:00+07:00",deadlineText:"Sabtu, 5 September 2026 • 23.59 WIB",details:"<ul><li>Username sesuai kreativitas.</li><li>Bio nama kelas + angkatan.</li><li>Untuk repost tugas infografis anggota.</li><li>Feed foto/biodata anggota dan pengurus kelas.</li><li>Buat sekreatif mungkin.</li></ul>"},
{id:"k3",number:3,title:"Membuat Liwetan — Day 3 🍱",deadline:null,deadlineText:"Tanggal pelaksanaan belum diketahui",details:"<strong>Minimal 4 jenis menu:</strong><ul><li>Karbohidrat/nasi liwet</li><li>Lauk protein utama</li><li>Lauk pendamping</li><li>Sayuran/urap/lalapan + sambal</li></ul>Utamakan makanan tradisional Nusantara non-mi. <strong>Budget:</strong> maksimal Rp500.000/kelompok.<br><br><strong>Penilaian:</strong> kelengkapan menu, estetika/kerapian, kekompakan/kerja sama, kebersihan/kepatuhan.",subtasks:[
{id:"l1",title:"Siapkan minimal 4 jenis menu",deadline:null,deadlineText:"Nasi liwet + protein + lauk pendamping + sayur/urap/lalapan + sambal"},
{id:"l2",title:"Penyajian & plating",deadline:null,deadlineText:"Kertas minyak bersih, menarik, unik, rapi"},
{id:"l3",title:"Pastikan budget maksimal Rp500.000",deadline:null,deadlineText:"Per kelompok"},
{id:"l4",title:"Bawa sendok pribadi/sarung tangan & tumbler",deadline:null,deadlineText:"Setiap peserta"},
{id:"l5",title:"Bawa trash bag & bersihkan tempat 100%",deadline:null,deadlineText:"Wajib setelah acara"}]}
],
angkatan:[
{id:"a1",number:1,title:"Menentukan Kandidat Calon Ketua Angkatan",deadline:"2026-09-05T23:59:00+07:00",deadlineText:"Sabtu, 5 September 2026",details:"<ul><li>Tentukan 6 calon kandidat ketua angkatan.</li><li>Laporkan kepada panitia humas (Kak Azza).</li></ul>"},
{id:"a2",number:2,title:"Membuat Desain Baju Batik Angkatan",deadline:"2026-10-05T23:59:00+07:00",deadlineText:"Senin, 5 Oktober 2026 • 23.59 WIB",details:"<ul><li>Perempuan: batik lengan panjang.</li><li>Laki-laki: lengan panjang/pendek sesuai kesepakatan.</li><li>Motif disepakati satu angkatan.</li><li>Warna bernuansa merah/maroon.</li><li>Laporkan ke panitia humas (Kak Azza).</li></ul>"},
{id:"a3",number:3,title:"Membuat Instagram Angkatan",deadline:"2026-09-30T23:59:00+07:00",deadlineText:"Rabu, 30 September 2026 • 23.59 WIB",details:"<ul><li>Nama Instagram angkatan 2026 kreatif.</li><li>Bio nama jurusan + angkatan.</li><li>Follow PGSD UNESA dan HMPPGSD.</li><li>Minimal 200 followers.</li><li>Dikoordinasikan pengurus angkatan.</li><li>Aktif untuk dokumentasi kegiatan.</li><li>Akun publik/tidak private.</li><li>Laporkan ke panitia humas (Kak Azza).</li></ul>"}
]};

